#!/usr/bin/env node
// brand.cjs : embeds the Learn brand assets into src/photos.js — the one sanctioned media door.
//
//   node tools/brand.cjs
//
// This film is a brand piece for the Learn page, so it deviates from the zero-asset house rule in
// exactly two ways, both through the photo door the media scan already exempts:
//   - the real logo (club_landing public/logo.png, trimmed) and the author photo, as FILM.PHOTOS
//   - the site's typefaces, Onest and JetBrains Mono (variable woff2, cyrillic + latin subsets),
//     as FILM.FONTS, loaded by core's photo-io lines before the first frame.
'use strict';

const fs = require('fs');
const path = require('path');
const C = require('./common.cjs');

const A = path.join(C.ROOT, 'assets');
const b64 = (f) => fs.readFileSync(f).toString('base64');

const photos = {
  logo: { file: 'brand/logo.png', mime: 'image/png', w: 512, h: 512 },
  author: { file: 'brand/vladilen.jpg', mime: 'image/jpeg', w: 256, h: 256 },
};
const CYR = 'U+0301,U+0400-045F,U+0490-0491,U+04B0-04B1,U+2116';
const LAT = 'U+0000-00FF,U+0131,U+0152-0153,U+02BB-02BC,U+02C6,U+02DA,U+02DC,U+0304,U+0308,U+0329,U+2000-206F,U+20AC,U+2122,U+2190-2199,U+2212,U+2215,U+FEFF,U+FFFD';
const fonts = [
  { family: 'Onest', file: 'fonts/onest-cyrillic-wght-normal.woff2', range: CYR },
  { family: 'Onest', file: 'fonts/onest-latin-wght-normal.woff2', range: LAT },
  { family: 'JetBrains Mono', file: 'fonts/jetbrains-mono-cyrillic-wght-normal.woff2', range: CYR },
  { family: 'JetBrains Mono', file: 'fonts/jetbrains-mono-latin-wght-normal.woff2', range: LAT },
];

let out = '// GENERATED by tools/brand.cjs from assets/ — do not edit by hand.\n';
out += 'window.FILM = window.FILM || {};\nFILM.PHOTOS = FILM.PHOTOS || {};\n';
for (const [id, p] of Object.entries(photos)) {
  out += `FILM.PHOTOS[${JSON.stringify(id)}] = { w: ${p.w}, h: ${p.h}, uri: 'data:${p.mime};base64,${b64(path.join(A, p.file))}' };\n`;
}
out += 'FILM.FONTS = [\n';
for (const f of fonts) {
  out += `  { family: ${JSON.stringify(f.family)}, weight: '100 900', range: ${JSON.stringify(f.range)}, uri: 'data:font/woff2;base64,${b64(path.join(A, f.file))}' },\n`;
}
out += '];\n';
fs.writeFileSync(path.join(C.SRC, 'photos.js'), out);
console.log(`wrote src/photos.js (${(out.length / 1024).toFixed(0)} KB): photos ${Object.keys(photos).join(', ')}; ${fonts.length} font faces`);
