// common.cjs : shared plumbing for snap, build, render and check.
'use strict';

const fs = require('fs');
const path = require('path');
const vm = require('vm');

const ROOT = path.resolve(__dirname, '..');
const SLUG = path.basename(ROOT).trim().replace(/\s+/g, '-'); // the project folder is named for the film's slug
const SRC = path.join(ROOT, 'src');
const FIX = path.join(__dirname, 'fixtures');
const TMP = path.join(ROOT, '.tmp');
/** A timeline's frame rate: raw FILM.TIMELINE or a normalized wrapper with .raw; 24 when undeclared. */
function fps(tl) {
  const raw = tl && tl.raw ? tl.raw : tl || {};
  return Number(raw.fps) || 24;
}
const FPS = fps({}); // drawn films stay at 24

function die(msg) {
  process.stderr.write(`\n[error] ${msg}\n`);
  process.exit(2);
}

/** --key value, --key=value, --flag. Numbers stay strings; callers convert. */
function parseArgs(argv, flags = []) {
  const out = { _: [] };
  for (let i = 0; i < argv.length; i++) {
    const a = argv[i];
    if (!a.startsWith('--')) {
      out._.push(a);
      continue;
    }
    const eq = a.indexOf('=');
    if (eq > 0) {
      out[a.slice(2, eq)] = a.slice(eq + 1);
      continue;
    }
    const key = a.slice(2);
    const next = argv[i + 1];
    if (flags.includes(key) || next === undefined || next.startsWith('--')) out[key] = true;
    else {
      out[key] = next;
      i++;
    }
  }
  return out;
}

/** Resolve a user path: absolute stays, relative is taken from the project root. */
function resolveOut(p) {
  return path.isAbsolute(p) ? p : path.join(ROOT, p);
}

function rel(p) {
  return path.relative(ROOT, p) || '.';
}

function normalizeTimeline(tl) {
  if (!tl || typeof tl !== 'object') throw new Error('FILM.TIMELINE is not an object');
  const shots = Array.isArray(tl.shots) ? tl.shots : [];
  let cursor = 0;
  const pick = (s, keys) => {
    for (const k of keys) if (s[k] != null && isFinite(Number(s[k]))) return Number(s[k]);
    return null;
  };
  const out = shots.map((s, i) => {
    let start = pick(s, ['start', 't0', 'from', 'in']);
    if (start == null) start = cursor;
    let end = pick(s, ['end', 't1', 'to', 'out']);
    if (end == null) {
      const d = pick(s, ['dur', 'duration', 'length']);
      end = d != null ? start + d : start;
    }
    cursor = end;
    let tr = s.transitionIn || null;
    if (typeof tr === 'string') tr = { kind: tr };
    if (tr) {
      tr = Object.assign({}, tr, {
        kind: String(tr.kind || tr.type || 'cut').toLowerCase(),
        dur: Number(tr.dur != null ? tr.dur : tr.duration != null ? tr.duration : 0.25),
      });
    }
    return Object.assign({}, s, { index: i, start, end, dur: end - start, transitionIn: tr });
  });
  const duration = tl.duration != null ? Number(tl.duration) : out.length ? out[out.length - 1].end : 0;
  return { raw: tl, shots: out, duration, hasDuration: tl.duration != null, bpm: tl.bpm, cues: tl.cues };
}

/** Evaluate a timeline file in a sandbox (no browser needed). */
function loadTimeline(file) {
  const code = fs.readFileSync(file, 'utf8');
  const noop = () => {};
  const libStub = new Proxy(function () {}, { get: () => libStub, apply: () => 0 });
  const FILM = { W: 1080, H: 1920, FPS, lib: libStub, scene: noop };
  // a timeline may declare its own frame size (photo-doodle films are square); mirrored back below
  const sandbox = { FILM, console, Math };
  sandbox.window = sandbox;
  sandbox.globalThis = sandbox;
  vm.createContext(sandbox);
  vm.runInContext(code, sandbox, { filename: file, timeout: 2000 });
  const tl = sandbox.FILM.TIMELINE || (sandbox.window.FILM && sandbox.window.FILM.TIMELINE);
  if (!tl) throw new Error(`${rel(file)} ran but did not set FILM.TIMELINE`);
  const out = normalizeTimeline(tl);
  out.width = tl.width != null && Number(tl.width) > 0 ? Number(tl.width) : 1080;
  out.height = tl.height != null && Number(tl.height) > 0 ? Number(tl.height) : 1920;
  return out;
}

/**
 * Work out every file to load, in contract order, and validate that the timeline and each
 * shot's file exist. Returns { files, timeline, base, sceneFiles, shotFile(id), musicFile, warnings }.
 *   fixtures: use tools/fixtures/{timeline.js,scenes,music.js} instead of src (or --fixtures=<dir> with that layout)
 *   only:     shot id; load only core, lib, timeline and that shot's file
 *   player:   include player.js (default true)
 *   needMusic: die when music.js is missing
 *   lenient:  report missing shot files in .problems instead of exiting (check.cjs)
 */
/**
 * Photo-doodle prelude, loaded after lib.js and before the timeline when present:
 *   src/photos.js  generated by tools/photos.cjs from assets/cut
 *   src/props.js   the shared doodle props
 *   src/cast.js    the film's recurring characters
 * A zero-asset film simply has none of them.
 */
// Retro mode adds src/pixel.js, sprites.js, chip.js, crt.js and manifest.js ahead of them, and a
// game film appends every src/game/*.js (sorted) after them.
function gameFiles() {
  const gameDir = path.join(SRC, 'game');
  return fs.existsSync(gameDir) ? fs.readdirSync(gameDir).filter((f) => f.endsWith('.js')).sort().map((f) => path.join(gameDir, f)) : [];
}

// base: a fixtures directory may supply its own copy of any prelude file (a retro fixture's sprites.js);
// src stays the source for the rest.
function preludeFiles(base = SRC) {
  const opt = ['pixel.js', 'sprites.js', 'chip.js', 'crt.js', 'manifest.js', 'photos.js', 'props.js', 'cast.js'];
  const pick = (f) => (base !== SRC && fs.existsSync(path.join(base, f)) ? path.join(base, f) : path.join(SRC, f));
  return [...opt.map(pick).filter((f) => fs.existsSync(f)), ...gameFiles()];
}

// music.js falls back to src like the prelude files: a fixtures dir without its own music.js uses
// src/music.js. The timeline and scenes always come from the fixtures dir.
function musicPath(base) {
  const own = path.join(base, 'music.js');
  return base !== SRC && !fs.existsSync(own) && fs.existsSync(path.join(SRC, 'music.js')) ? path.join(SRC, 'music.js') : own;
}

/**
 * The game page's sources: core, lib, the retro kit, every src/game/*.js in sorted order, timeline,
 * music, shell. No scenes, no film player; every file must exist.
 */
function gameSources() {
  const game = gameFiles();
  if (!game.length) die('src/game has no .js files; the game page needs the engine.');
  const files = [
    ...['core.js', 'lib.js', 'pixel.js', 'sprites.js', 'chip.js', 'crt.js', 'manifest.js'].map((f) => path.join(SRC, f)),
    ...game,
    ...['timeline.js', 'music.js', 'shell.js'].map((f) => path.join(SRC, f)),
  ];
  const missing = files.filter((f) => !fs.existsSync(f));
  if (missing.length) die(`the game page is missing ${missing.map(rel).join(', ')}`);
  let timeline;
  try {
    timeline = loadTimeline(path.join(SRC, 'timeline.js'));
  } catch (e) {
    die(`src/timeline.js failed to evaluate: ${e.message}`);
  }
  return { files, timeline, base: SRC, label: 'src', scenesDir: null, sceneFiles: [], shotFile: () => null, musicFile: path.join(SRC, 'music.js'), warnings: [], problems: [], game: true };
}

function sources({ fixtures = false, only = null, player = true, needMusic = false, lenient = false } = {}) {
  // fixtures may be true (tools/fixtures) or a directory path laid out the same way
  const base = fixtures ? (typeof fixtures === 'string' ? resolveOut(fixtures) : FIX) : SRC;
  const label = fixtures ? rel(base) : 'src';
  const core = path.join(SRC, 'core.js');
  const lib = path.join(SRC, 'lib.js');
  for (const f of [core, lib]) if (!fs.existsSync(f)) die(`${rel(f)} is missing.`);
  const tlFile = path.join(base, 'timeline.js');
  if (!fs.existsSync(tlFile)) {
    die(
      `${label}/timeline.js is missing.\n` +
        (fixtures
          ? 'The fixture timeline should live at tools/fixtures/timeline.js.'
          : 'The storyboard agent writes src/timeline.js. Until it exists, run with --fixtures to exercise the tools.')
    );
  }
  let timeline;
  try {
    timeline = loadTimeline(tlFile);
  } catch (e) {
    die(`${label}/timeline.js failed to evaluate: ${e.message}`);
  }
  const scenesDir = path.join(base, 'scenes');
  const sceneFiles = fs.existsSync(scenesDir)
    ? fs.readdirSync(scenesDir).filter((f) => f.endsWith('.js')).sort().map((f) => path.join(scenesDir, f))
    : [];
  const shotFile = (shot) => {
    if (!shot.file) return null;
    return path.join(scenesDir, path.basename(String(shot.file)));
  };
  const problems = [];
  for (const shot of timeline.shots) {
    if (!shot.file) problems.push(`shot '${shot.id}' has no "file" in ${label}/timeline.js`);
    else if (!fs.existsSync(shotFile(shot))) problems.push(`shot '${shot.id}' names file '${shot.file}', which does not exist at ${rel(shotFile(shot))}`);
  }
  const warnings = [];
  let files;
  if (only) {
    const shot = timeline.shots.find((s) => s.id === only);
    if (!shot) die(`--only: no shot with id '${only}' in ${label}/timeline.js. Ids: ${timeline.shots.map((s) => s.id).join(', ')}`);
    const f = shotFile(shot);
    if (!f || !fs.existsSync(f)) die(`shot '${only}': ${problems.find((p) => p.includes(`'${only}'`)) || 'file missing'}`);
    files = [core, lib, ...preludeFiles(base), tlFile, f];
  } else {
    if (problems.length && !lenient) die(`timeline problems:\n  - ${problems.join('\n  - ')}`);
    files = [core, lib, ...preludeFiles(base), tlFile, ...sceneFiles];
    const musicFile = musicPath(base);
    if (fs.existsSync(musicFile)) files.push(musicFile);
    else if (needMusic) die(`${label}/music.js is missing. The music agent writes it. Pass --silent to render without it.`);
    else warnings.push(`${label}/music.js is missing (no audio)`);
    if (player) files.push(path.join(SRC, 'player.js'));
  }
  const musicFile = musicPath(base);
  return {
    files,
    timeline,
    base,
    label,
    scenesDir,
    sceneFiles,
    shotFile,
    musicFile: fs.existsSync(musicFile) ? musicFile : null,
    warnings,
    problems,
  };
}

// Temporary files and folders removed when the process exits for any reason (including die()).
const exitCleanup = new Set();
process.on('exit', () => {
  for (const p of exitCleanup) {
    try {
      fs.rmSync(p, { recursive: true, force: true });
    } catch (e) {
      /* best effort */
    }
  }
});
function cleanupOnExit(p) {
  exitCleanup.add(p);
  return () => exitCleanup.delete(p);
}

function uniqueName(prefix) {
  return `${prefix}-${process.pid}-${Date.now().toString(36)}-${Math.random().toString(36).slice(2, 8)}`;
}

// Harness injected into tool pages only (never shipped). It may use performance.now.
const HARNESS = `
window.__h = {
  mount(scale, only) {
    const c = document.createElement('canvas');
    c.id = 'tool-canvas';
    document.body.appendChild(c);
    FILM.mount(c, { scale, readback: true });
    FILM.strict = false;
    FILM.only = only || null;
    return { w: c.width, h: c.height, duration: FILM.DURATION, frames: FILM.FRAMES };
  },
  render(T, o) {
    FILM.errors = [];
    FILM.post = !(o && o.post === false);
    const text = o && o.text ? this._catchText() : null;
    const t0 = performance.now();
    const shot = FILM.renderFrame(T);
    FILM.post = true;
    FILM.ctx.getImageData(0, 0, 1, 1); // force the deferred raster to run so the timing is real
    const ms = performance.now() - t0;
    const drawn = text ? text.stop() : [];
    return { ms, shot: shot ? shot.id : null, text: drawn, errors: FILM.errors.map(e => ({ message: e.message, stack: e.stack, shot: e.shot, missing: !!e.missing })) };
  },
  // Every string the frame paints, with the y it really lands on: the canvas is wrapped rather than
  // lib.text, so computed positions, camera transforms and raw ctx.fillText all land as one number.
  _catchText() {
    const ctx = FILM.ctx;
    const hits = [];
    const S = FILM.S || 1;
    const wrap = (name) => {
      const orig = ctx[name].bind(ctx);
      ctx[name] = (str, x, y, ...rest) => {
        const m = ctx.getTransform();
        // the ink's bottom, not the baseline: descenders hang below an alphabetic baseline, and a
        // 'top' baseline puts the whole glyph body below y
        const size = parseFloat((/(\d*\.?\d+)px/.exec(ctx.font) || [0, 16])[1]) || 16;
        const b = ctx.textBaseline;
        const drop = b === 'top' || b === 'hanging' ? size : b === 'middle' ? size * 0.6 : b === 'bottom' || b === 'ideographic' ? 0 : size * 0.25;
        const yb = y + drop;
        const yt = yb - size; // the ink's top: one em above its bottom
        // the ink's horizontal extent from the measured advance and the alignment (measureText paints nothing)
        const wd = ctx.measureText(String(str)).width;
        const a = ctx.textAlign;
        const x0 = a === 'center' ? x - wd / 2 : a === 'right' || a === 'end' ? x - wd : x;
        const xs = [m.a * x0 + m.c * y + m.e, m.a * (x0 + wd) + m.c * y + m.e];
        hits.push({
          str: String(str).slice(0, 40), size,
          y: (m.b * x + m.d * y + m.f) / S, bottom: (m.b * x + m.d * yb + m.f) / S, top: (m.b * x + m.d * yt + m.f) / S,
          left: Math.min(xs[0], xs[1]) / S, right: Math.max(xs[0], xs[1]) / S,
        });
        return orig(str, x, y, ...rest);
      };
      return () => { ctx[name] = orig; };
    };
    const undo = [wrap('fillText'), wrap('strokeText')];
    // retro: pxtext paints glyphs with fillRect and reports its box (final canvas px) through FILM.__textProbe
    if (FILM.retro) {
      const prev = FILM.__textProbe;
      FILM.__textProbe = (str, x, y, w, h) => {
        hits.push({ str: String(str).slice(0, 40), size: h / S, y: (y + h) / S, bottom: (y + h) / S, top: y / S, left: x / S, right: (x + w) / S });
      };
      undo.push(() => { FILM.__textProbe = prev; });
    }
    return { stop() { undo.forEach((u) => u()); return hits; } };
  },
  png() {
    return FILM.canvas.toDataURL('image/png').slice(22);
  },
  hash() {
    const c = FILM.canvas;
    const d = FILM.ctx.getImageData(0, 0, c.width, c.height).data;
    let h1 = 0x811c9dc5 | 0, h2 = 0x01000193 | 0;
    for (let i = 0; i < d.length; i++) {
      h1 = Math.imul(h1 ^ d[i], 0x01000193);
      if ((i & 3) === 3) h2 = Math.imul(h2 ^ h1, 0x5bd1e995);
    }
    return (h1 >>> 0).toString(16).padStart(8, '0') + (h2 >>> 0).toString(16).padStart(8, '0');
  },
  sheetInit(n, cols, thumbW, labelH) {
    const c = FILM.canvas;
    const th = Math.round(thumbW * c.height / c.width);
    const rows = Math.ceil(n / cols);
    const pad = 12;
    const s = document.createElement('canvas');
    s.width = cols * (thumbW + pad) + pad;
    s.height = rows * (th + labelH + pad) + pad;
    const g = s.getContext('2d');
    g.fillStyle = '#141414';
    g.fillRect(0, 0, s.width, s.height);
    this.sheet = { s, g, cols, thumbW, th, labelH, pad };
  },
  sheetAdd(i, label) {
    const { g, cols, thumbW, th, labelH, pad } = this.sheet;
    const x = pad + (i % cols) * (thumbW + pad);
    const y = pad + Math.floor(i / cols) * (th + labelH + pad);
    g.imageSmoothingQuality = 'high';
    g.drawImage(FILM.canvas, x, y, thumbW, th);
    g.fillStyle = '#e8e8e8';
    g.font = '600 ' + Math.round(labelH * 0.42) + 'px ui-monospace, Menlo, monospace';
    g.textBaseline = 'middle';
    g.fillText(label[0], x + 2, y + th + labelH * 0.32);
    g.fillStyle = '#9a9a9a';
    g.font = Math.round(labelH * 0.34) + 'px ui-monospace, Menlo, monospace';
    g.fillText(label[1], x + 2, y + th + labelH * 0.74);
  },
  sheetPng() {
    return this.sheet.s.toDataURL('image/png').slice(22);
  },
  async audio(from, to, sampleRate) {
    if (!FILM.audio || typeof FILM.audio.render !== 'function') return { missing: true };
    const len = Math.max(1, Math.round((to - from) * sampleRate));
    const ctx = new OfflineAudioContext(2, len, sampleRate);
    await FILM.audio.render(ctx, { start: from, dest: ctx.destination });
    const buf = await ctx.startRendering();
    const L = buf.getChannelData(0), R = buf.numberOfChannels > 1 ? buf.getChannelData(1) : L;
    const inter = new Float32Array(len * 2);
    let peak = 0;
    for (let i = 0; i < len; i++) {
      inter[2 * i] = L[i];
      inter[2 * i + 1] = R[i];
      const a = Math.max(Math.abs(L[i]), Math.abs(R[i]));
      if (a > peak) peak = a;
    }
    const bytes = new Uint8Array(inter.buffer);
    let bin = '';
    const CH = 0x8000;
    for (let i = 0; i < bytes.length; i += CH) bin += String.fromCharCode.apply(null, bytes.subarray(i, i + CH));
    return { b64: btoa(bin), frames: len, peak };
  },
};
`;

// Retro helpers (the console palette audit and the TV's proof reads), installed only on a page that
// loads the retro kit, so a drawn or doodle page runs exactly the harness above.
const RETRO_HARNESS = `
Object.assign(window.__h, {
  // Console-palette audit (check 8): the allowed colours once (default FILM.retro.NES), then the current
  // frame. With a console frame buffer (FILM.native and FILM.crt) every native pixel is read: the CRT
  // output is the TV and may hold any colour. Otherwise (or with output=true) every 8th pixel of each
  // row of the output canvas, the row's phase shifting by one so all 8 columns of an 8x8 pixel are sampled.
  nesInit(list) {
    const src = list || (FILM.retro && FILM.retro.NES) || [];
    this._nes = new Set(Array.from(src).map((h) => parseInt(String(h).replace('#', ''), 16)));
  },
  nesAudit(output) {
    const nb = !output && FILM.native && FILM.crt ? FILM.native() : null;
    const c = nb ? nb.canvas : FILM.canvas;
    const g = nb ? nb.ctx : FILM.ctx;
    const w = c.width, h = c.height;
    const d = g.getImageData(0, 0, w, h).data;
    if (!this._nes) this.nesInit();
    const ok = this._nes;
    const step = nb ? 1 : 8;
    let n = 0, bad = 0;
    const seen = new Map();
    for (let y = 0; y < h; y++) {
      for (let x = nb ? 0 : y & 7; x < w; x += step) {
        const i = (y * w + x) * 4;
        const v = (d[i] << 16) | (d[i + 1] << 8) | d[i + 2];
        n++;
        if (!ok.has(v)) {
          bad++;
          if (seen.size < 6 && !seen.has(v)) seen.set(v, x + ',' + y);
        }
      }
    }
    return { n, bad, source: nb ? 'native' : 'output', colours: [...seen].map(([v, at]) => '#' + v.toString(16).toUpperCase().padStart(6, '0') + ' at ' + at) };
  },
  // the TV's mode ('crt' | 'clean') and what actually ran
  crtMode(mode) {
    if (window.FILM && FILM.crt && mode) FILM.crt.mode = mode;
    return this.crtInfo();
  },
  crtInfo() {
    const c = window.FILM && FILM.crt;
    return c ? { mode: c.mode, backend: c.backend, renderer: c.renderer || null, overlays: c.overlays ? Object.assign({}, c.overlays) : null } : null;
  },
  // the proof layers ({ input, caption } booleans), and what they cover
  crtOverlays(o) {
    const c = window.FILM && FILM.crt;
    if (!c) return null;
    if (o) c.overlays = Object.assign({}, c.overlays, o);
    return {
      overlays: Object.assign({}, c.overlays),
      input: c.inputWindows ? c.inputWindows() : [],
      caption: c.captionWindow ? c.captionWindow() : null,
      marks: c.marks ? c.marks() : null,
    };
  },
  // FNV-1a of a region of the output (x, y, w, h in output px)
  regionHash(x, y, w, h) {
    const d = FILM.ctx.getImageData(x, y, w, h).data;
    let h1 = 0x811c9dc5 | 0;
    for (let i = 0; i < d.length; i++) h1 = Math.imul(h1 ^ d[i], 0x01000193);
    return (h1 >>> 0).toString(16).padStart(8, '0');
  },
  // Luminance of the TV output (check 11): mean and max over the frame, the mean of a centre box of
  // half-size box px, and the scanline modulation: the strongest DFT amplitude (relative to the mean)
  // of the centre band's vertical luma profile at a period within 12% of pitch px.
  lumaStats(box, pitch) {
    const c = FILM.canvas;
    const w = c.width, h = c.height;
    const d = FILM.ctx.getImageData(0, 0, w, h).data;
    const L = (i) => 0.2126 * d[i] + 0.7152 * d[i + 1] + 0.0722 * d[i + 2];
    let sum = 0, max = 0, n = 0;
    for (let i = 0; i < d.length; i += 16) {
      const v = L(i);
      sum += v;
      if (v > max) max = v;
      n++;
    }
    let cs = 0, cn = 0;
    for (let y = Math.max(0, (h >> 1) - box); y < Math.min(h, (h >> 1) + box); y++) {
      for (let x = Math.max(0, (w >> 1) - box); x < Math.min(w, (w >> 1) + box); x++) {
        const v = L((y * w + x) * 4);
        cs += v;
        cn++;
        if (v > max) max = v;
      }
    }
    const y0 = Math.round(h * 0.4), y1 = Math.round(h * 0.6), x0 = Math.round(w * 0.45), x1 = Math.round(w * 0.55);
    const prof = [];
    for (let y = y0; y < y1; y++) {
      let a = 0, k = 0;
      for (let x = x0; x < x1; x++, k++) a += L((y * w + x) * 4);
      prof.push(a / k);
    }
    const pm = prof.reduce((a, b) => a + b, 0) / prof.length;
    let best = { period: 0, amp: 0 };
    for (let per = pitch * 0.88; per <= pitch * 1.12; per += pitch * 0.005) {
      let re = 0, im = 0;
      for (let i = 0; i < prof.length; i++) {
        re += (prof[i] - pm) * Math.cos((2 * Math.PI * i) / per);
        im += (prof[i] - pm) * Math.sin((2 * Math.PI * i) / per);
      }
      const amp = pm > 0 ? (2 * Math.hypot(re, im)) / prof.length / pm : 0;
      if (amp > best.amp) best = { period: per, amp };
    }
    return { mean: sum / n / 255, max: max / 255, centre: cn ? cs / cn / 255 : 0, scan: best };
  },
});
`;
const RETRO_KIT = new Set(['pixel.js', 'chip.js', 'crt.js']);

function pageHtml(files, { title = 'tool' } = {}) {
  const tags = files.map((f) => `<script src="file://${encodeURI(f)}"></script>`).join('\n');
  const retro = files.some((f) => RETRO_KIT.has(path.basename(f)));
  return `<!doctype html>
<html><head><meta charset="utf-8"><title>${title}</title>
<style>html,body{margin:0;background:#000}</style>
<script>window.__loadErrors=[];window.addEventListener('error',function(e){window.__loadErrors.push({message:e.message,file:(e.filename||'').split('/').pop(),line:e.lineno,col:e.colno});});</script>
</head><body>
${tags}
<script>${HARNESS}</script>
${retro ? `<script>${RETRO_HARNESS}</script>\n` : ''}</body></html>`;
}

async function launch(extraArgs = []) {
  let chromium;
  try {
    ({ chromium } = require(path.join(__dirname, 'node_modules', 'playwright')));
  } catch (e) {
    die(`playwright is not installed in tools/node_modules (${e.message})`);
  }
  // Retro films pin WebGL to SwiftShader so every machine hashes the same CRT pixels; FILM_GL=gpu opts out.
  const gl = fs.existsSync(path.join(SRC, 'crt.js')) && process.env.FILM_GL !== 'gpu' ? ['--use-angle=swiftshader', '--enable-unsafe-swiftshader'] : [];
  const net = process.env.FILM_NO_NET === '1' ? ['--host-resolver-rules=MAP * ~NOTFOUND , EXCLUDE localhost, EXCLUDE 127.0.0.1'] : [];
  return chromium.launch({ ...((process.env.CHROMIUM_PATH || (fs.existsSync('/opt/pw-browsers/chromium') ? '/opt/pw-browsers/chromium' : '')) ? { executablePath: process.env.CHROMIUM_PATH || '/opt/pw-browsers/chromium' } : {}), args: ['--allow-file-access-from-files', '--disable-background-timer-throttling', ...gl, ...net, ...extraArgs] });
}

/**
 * Open a page with the given files loaded (contract order), mount the canvas at scale.
 *   only: shot id when only that shot's file is loaded (sets FILM.only, so core skips transitions from unloaded shots)
 * Returns { page, info, state, loadErrors, tmpFile, pageErrors, consoleErrors, reopen, close }.
 * reopen() navigates the same page again: fresh JS state, nothing drawn yet, canvas mounted.
 */
async function openPage(browser, files, { scale = 1, prefix = 'page', query = '?render=1', only = null } = {}) {
  fs.mkdirSync(TMP, { recursive: true });
  const tmpFile = path.join(TMP, uniqueName(prefix) + '.html');
  fs.writeFileSync(tmpFile, pageHtml(files, { title: prefix }));
  const forget = cleanupOnExit(tmpFile);
  const context = await browser.newContext({ viewport: { width: 540, height: 960 }, deviceScaleFactor: 1 });
  const page = await context.newPage();
  const pageErrors = [];
  const consoleErrors = [];
  page.on('pageerror', (e) => pageErrors.push(e.message));
  page.on('console', (m) => {
    if (m.type() === 'error') consoleErrors.push(m.text());
  });
  const pg = { page, info: null, state: null, loadErrors: [], pageErrors, consoleErrors, tmpFile };
  pg.reopen = async () => {
    await page.goto('file://' + tmpFile + query, { waitUntil: 'load' });
    pg.loadErrors = await page.evaluate(() => window.__loadErrors);
    pg.state = await page.evaluate(() => ({
      hasFilm: typeof window.FILM === 'object',
      hasLib: !!(window.FILM && window.FILM.lib),
      hasTimeline: !!(window.FILM && window.FILM.TIMELINE),
      registered: window.FILM && window.FILM.registered ? window.FILM.registered : [],
      regErrors: window.FILM && window.FILM.errors ? window.FILM.errors.map((e) => e.message) : [],
      hasAudio: !!(window.FILM && window.FILM.audio && typeof window.FILM.audio.render === 'function'),
    }));
    pg.info = null;
    await page.evaluate(() => (window.FILM && window.FILM.loadPhotos ? window.FILM.loadPhotos() : 0));
    // The hand-lettering face resolves asynchronously: a frame drawn before it is ready uses a
    // fallback and hashes differently from the same frame drawn later (flaky determinism).
    await page.evaluate(async () => {
      if (!document.fonts) return 0;
      await document.fonts.load('600 46px Onest', 'АБВабв abc 0123'); await document.fonts.load('500 30px "JetBrains Mono"', 'АБВабв abc 0123');
      await document.fonts.ready;
      return document.fonts.status;
    });
    if (pg.state.hasFilm && pg.state.hasTimeline) pg.info = await page.evaluate(([s, o]) => window.__h.mount(s, o), [scale, only]);
    return pg.info;
  };
  let closed = false;
  pg.close = async () => {
    if (closed) return;
    closed = true;
    await context.close().catch(() => {});
    fs.rmSync(tmpFile, { force: true });
    forget();
  };
  try {
    await pg.reopen();
  } catch (e) {
    await pg.close();
    throw e;
  }
  return pg;
}

function writeWavFloat(file, b64, channels, sampleRate) {
  const data = Buffer.from(b64, 'base64');
  const header = Buffer.alloc(44);
  header.write('RIFF', 0);
  header.writeUInt32LE(36 + data.length, 4);
  header.write('WAVE', 8);
  header.write('fmt ', 12);
  header.writeUInt32LE(16, 16);
  header.writeUInt16LE(3, 20); // IEEE float
  header.writeUInt16LE(channels, 22);
  header.writeUInt32LE(sampleRate, 24);
  header.writeUInt32LE(sampleRate * channels * 4, 28);
  header.writeUInt16LE(channels * 4, 32);
  header.writeUInt16LE(32, 34);
  header.write('data', 36);
  header.writeUInt32LE(data.length, 40);
  fs.writeFileSync(file, Buffer.concat([header, data]));
}

// Patterns that would mean the shipped HTML loads or embeds media instead of computing it.
const FORBIDDEN = [
  { name: '<img>', re: /<img\b/gi },
  { name: 'new Image/Audio/Video', re: /\bnew\s+(?:(?:window|self|globalThis)\s*\.\s*)?(?:Image|Audio|Video)\b/g },
  { name: 'createElement(media tag)', re: /createElement(?:NS)?\s*\(\s*(?:[^,()]*,\s*)?['"`]\s*(?:img|image|video|audio|source|picture|track|iframe|object|embed|link)\s*['"`]/gi },
  { name: '.src/.srcset assignment', re: /\.\s*(?:src|srcset)\s*=(?!=)/g },
  { name: 'setAttribute(src/srcset/href)', re: /setAttribute(?:NS)?\s*\(\s*(?:[^,()]*,\s*)?['"`](?:src|srcset|href|xlink:href)['"`]/gi },
  { name: 'fetch(', re: /\bfetch\s*\(/g },
  { name: 'XMLHttpRequest', re: /XMLHttpRequest/g },
  { name: 'CSS url(', re: /\burl\s*\(/g },
  { name: 'data: URL', re: /data:[a-z0-9.+-]+\/[a-z0-9.+-]+/gi },
  { name: 'base64', re: /base64/gi },
  { name: 'atob/btoa', re: /\b(atob|btoa)\s*\(/g },
  { name: '<audio>/<video>/<source>/<iframe>/<object>/<embed>', re: /<(audio|video|source|iframe|object|embed)\b/gi },
  { name: '<link>', re: /<link\b/gi },
  { name: 'external <script src>', re: /<script\b[^>]*\bsrc\s*=/gi },
  { name: '@font-face / @import', re: /@(font-face|import)\b/gi },
  { name: 'FontFace', re: /\bFontFace\b/g },
  { name: 'dynamic import(', re: /\bimport\s*\(/g },
  { name: 'WebSocket/EventSource/sendBeacon', re: /\b(WebSocket|EventSource|sendBeacon)\b/g },
  { name: 'createObjectURL', re: /createObjectURL/g },
  { name: 'decodeAudioData', re: /decodeAudioData/g },
  { name: 'media file name', re: /["'`][^"'`\n]*\.(png|jpe?g|gif|webp|avif|svg|bmp|ico|mp3|wav|ogg|oga|m4a|aac|flac|mp4|webm|mov|woff2?|ttf|otf|eot)["'`]/gi },
];

// Photographs are the one sanctioned media, and only through the two doors that put them there: the
// generated src/photos.js section, and core's own loader lines marked photo-io. A marker copied into
// a scene file exempts nothing — the scope check below is on the file, not just the comment.
function scanForbidden(html) {
  const hits = [];
  const lines = html.split('\n');
  const exempt = new Set();
  let inPhotos = false;
  let inCore = false;
  for (let i = 0; i < lines.length; i++) {
    const head = lines[i].startsWith('// ---- ') ? lines[i].slice(8).replace(/\\/g, '/') : null;
    if (head !== null) {
      inPhotos = head === 'src/photos.js';
      inCore = head === 'src/core.js';
    } else if (lines[i] === '</script>') {
      inPhotos = false;
      inCore = false;
    }
    if (inPhotos || (inCore && lines[i].includes('/* photo-io */'))) exempt.add(i);
  }
  for (const f of FORBIDDEN) {
    for (let i = 0; i < lines.length; i++) {
      if (exempt.has(i)) continue;
      f.re.lastIndex = 0;
      let m;
      while ((m = f.re.exec(lines[i]))) {
        const col = m.index;
        hits.push({ pattern: f.name, line: i + 1, text: lines[i].slice(Math.max(0, col - 40), col + 60).trim() });
        if (!f.re.global) break;
      }
    }
  }
  return hits;
}

function fmtT(T) {
  return T.toFixed(3);
}

module.exports = {
  ROOT,
  SLUG,
  SRC,
  FIX,
  TMP,
  FPS,
  fps,
  die,
  parseArgs,
  resolveOut,
  rel,
  loadTimeline,
  normalizeTimeline,
  sources,
  uniqueName,
  cleanupOnExit,
  pageHtml,
  preludeFiles,
  gameSources,
  launch,
  openPage,
  writeWavFloat,
  fmtT,
  FORBIDDEN,
  scanForbidden,
};
