#!/usr/bin/env node
// photos.cjs : embed assets/cut/*.webp (background-removed photos) into src/photos.js.
//
//   node tools/photos.cjs
//
// Each file becomes FILM.PHOTOS[<basename>] = { w, h, uri }. Scenes draw them with lib.photo(ctx, id, ...).
// Sizes are read from the WebP header (VP8X canvas), so no image library is needed.
'use strict';

const fs = require('fs');
const path = require('path');
const C = require('./common.cjs');

const DIR = path.join(C.ROOT, 'assets', 'cut');
const OUT = path.join(C.SRC, 'photos.js');

function webpSize(buf) {
  if (buf.toString('ascii', 0, 4) !== 'RIFF' || buf.toString('ascii', 8, 12) !== 'WEBP') throw new Error('not a WebP');
  const kind = buf.toString('ascii', 12, 16);
  if (kind === 'VP8X') return { w: 1 + buf.readUIntLE(24, 3), h: 1 + buf.readUIntLE(27, 3) };
  if (kind === 'VP8L') {
    const b = buf.readUInt32LE(21);
    return { w: 1 + (b & 0x3fff), h: 1 + ((b >> 14) & 0x3fff) };
  }
  if (kind === 'VP8 ') return { w: buf.readUInt16LE(26) & 0x3fff, h: buf.readUInt16LE(28) & 0x3fff };
  throw new Error(`unknown WebP chunk ${kind}`);
}

const files = fs.existsSync(DIR) ? fs.readdirSync(DIR).filter((f) => f.endsWith('.webp')).sort() : [];
const lines = ['/* photos.js : GENERATED by tools/photos.cjs from assets/cut. Do not edit. */', '(function () {', "  'use strict';", '  const P = window.FILM.PHOTOS;'];
let bytes = 0;
for (const f of files) {
  const buf = fs.readFileSync(path.join(DIR, f));
  const { w, h } = webpSize(buf);
  const id = path.basename(f, '.webp');
  bytes += buf.length;
  lines.push(`  P[${JSON.stringify(id)}] = { w: ${w}, h: ${h}, uri: 'data:image/webp;base64,${buf.toString('base64')}' };`);
  console.log(`  ${id}  ${w}x${h}  ${(buf.length / 1024).toFixed(0)} KB`);
}
lines.push('})();', '');
fs.writeFileSync(OUT, lines.join('\n'));
console.log(`${files.length} photos -> ${C.rel(OUT)} (${(bytes / 1024 / 1024).toFixed(2)} MB of image data)`);
