// GENERATED by tools/cuts.cjs (learn-60-page-subtitled). Edit tools/cuts.cjs, not this file.
FILM.TIMELINE = {
  "title": "learn",
  "variant": "learn-60-page-subtitled",
  "cut": 60,
  "ending": "page",
  "subtitles": true,
  "bpm": 120,
  "fps": 25,
  "width": 1920,
  "height": 1080,
  "duration": 60,
  "shots": [
    {
      "id": "s01",
      "file": "01-question.js",
      "start": 0,
      "end": 4,
      "mode": "none",
      "cut": 60,
      "title": "Знакомая ситуация",
      "brief": "see docs/storyboard.md s01"
    },
    {
      "id": "s02",
      "file": "02-guide.js",
      "start": 4,
      "end": 9,
      "mode": "none",
      "cut": 60,
      "title": "Появляется точка входа",
      "brief": "see docs/storyboard.md s02"
    },
    {
      "id": "s03",
      "file": "03-routes.js",
      "start": 9,
      "end": 12,
      "mode": "none",
      "cut": 60,
      "title": "Выбор из трёх задач",
      "brief": "see docs/storyboard.md s03"
    },
    {
      "id": "s04",
      "file": "04-agent.js",
      "start": 12,
      "end": 18,
      "mode": "none",
      "cut": 60,
      "title": "Собрать первого агента",
      "brief": "see docs/storyboard.md s04"
    },
    {
      "id": "s05",
      "file": "05-engineering.js",
      "start": 18,
      "end": 24,
      "mode": "none",
      "cut": 60,
      "title": "Разобраться в AI-инженерии",
      "brief": "see docs/storyboard.md s05"
    },
    {
      "id": "s06",
      "file": "06-project.js",
      "start": 24,
      "end": 30,
      "mode": "none",
      "cut": 60,
      "title": "Довести свой проект до результата",
      "brief": "see docs/storyboard.md s06",
      "transitionIn": {
        "kind": "fade",
        "dur": 0.32
      }
    },
    {
      "id": "s07",
      "file": "07-inside.js",
      "start": 30,
      "end": 35,
      "mode": "none",
      "cut": 60,
      "title": "Что внутри шага",
      "brief": "see docs/storyboard.md s07",
      "transitionIn": {
        "kind": "fade",
        "dur": 0.32
      }
    },
    {
      "id": "s08",
      "file": "08-practice.js",
      "start": 35,
      "end": 40,
      "mode": "none",
      "cut": 60,
      "title": "Сделать на своей задаче",
      "brief": "see docs/storyboard.md s08"
    },
    {
      "id": "s09",
      "file": "09-progress.js",
      "start": 40,
      "end": 45,
      "mode": "none",
      "cut": 60,
      "title": "Своё продвижение",
      "brief": "see docs/storyboard.md s09"
    },
    {
      "id": "s10",
      "file": "10-results.js",
      "start": 45,
      "end": 50,
      "mode": "none",
      "cut": 60,
      "title": "Что останется",
      "brief": "see docs/storyboard.md s10",
      "transitionIn": {
        "kind": "fade",
        "dur": 0.32
      }
    },
    {
      "id": "s11",
      "file": "11-free.js",
      "start": 50,
      "end": 54,
      "mode": "none",
      "cut": 60,
      "title": "Снять барьер",
      "brief": "see docs/storyboard.md s11"
    },
    {
      "id": "s12",
      "file": "12-cta.js",
      "start": 54,
      "end": 60,
      "mode": "none",
      "cut": 60,
      "title": "Выбрать маршрут",
      "brief": "see docs/storyboard.md s12"
    }
  ],
  "subs": [
    {
      "t0": 0.3,
      "t1": 3.8,
      "text": "Смотришь про AI. А на практике с чего начать?"
    },
    {
      "t0": 4.2,
      "t1": 8.8,
      "text": "В этом бесплатном гиде всё собрано вокруг твоей задачи."
    },
    {
      "t0": 9.1,
      "t1": 11.9,
      "text": "Выбери один из трёх маршрутов."
    },
    {
      "t0": 12.2,
      "t1": 17.8,
      "text": "Настрой агента под свой проект: задай правила, дай задачу и проверь результат."
    },
    {
      "t0": 18.2,
      "t1": 23.8,
      "text": "Разберись в AI-инженерии: как связаны модель, инструменты, знания и проверка."
    },
    {
      "t0": 24.2,
      "t1": 29.8,
      "text": "Сдвинь свой проект с места: выбери результат и составь план на неделю."
    },
    {
      "t0": 30.2,
      "t1": 34.8,
      "text": "В каждом шаге: видео, материалы и задание для практики."
    },
    {
      "t0": 35.1,
      "t1": 39.9,
      "text": "Возьми шаблон, примени к своей задаче и проверь, что получилось."
    },
    {
      "t0": 40.2,
      "t1": 44.8,
      "text": "Отметь выполненный шаг. Продолжишь здесь же, в своём темпе."
    },
    {
      "t0": 45.2,
      "t1": 49.8,
      "text": "На руках — бриф агента, схема или план твоего проекта."
    },
    {
      "t0": 50.2,
      "t1": 53.8,
      "text": "Материалы гида доступны бесплатно и без регистрации."
    },
    {
      "t0": 54.3,
      "t1": 58.6,
      "text": "Выбери маршрут ниже и сделай первый шаг сегодня."
    }
  ],
  "cues": [
    {
      "t": 0,
      "kind": "open"
    },
    {
      "t": 0.3,
      "kind": "tab"
    },
    {
      "t": 0.7,
      "kind": "tab"
    },
    {
      "t": 1.1,
      "kind": "tab"
    },
    {
      "t": 2.4,
      "kind": "question"
    },
    {
      "t": 4,
      "kind": "assemble"
    },
    {
      "t": 5,
      "kind": "logo"
    },
    {
      "t": 6.4,
      "kind": "card"
    },
    {
      "t": 7.1,
      "kind": "card"
    },
    {
      "t": 7.8,
      "kind": "card"
    },
    {
      "t": 9,
      "kind": "tick"
    },
    {
      "t": 9.2,
      "kind": "tick"
    },
    {
      "t": 9.4,
      "kind": "tick"
    },
    {
      "t": 11.2,
      "kind": "zoom"
    },
    {
      "t": 12,
      "kind": "section"
    },
    {
      "t": 13.2,
      "kind": "type"
    },
    {
      "t": 13.8,
      "kind": "type"
    },
    {
      "t": 14.4,
      "kind": "type"
    },
    {
      "t": 15,
      "kind": "handoff"
    },
    {
      "t": 16.9,
      "kind": "click"
    },
    {
      "t": 17.3,
      "kind": "verified"
    },
    {
      "t": 18,
      "kind": "section"
    },
    {
      "t": 19.2,
      "kind": "connect"
    },
    {
      "t": 20.1,
      "kind": "connect"
    },
    {
      "t": 21,
      "kind": "pulse"
    },
    {
      "t": 22.2,
      "kind": "connect"
    },
    {
      "t": 23.2,
      "kind": "sheet"
    },
    {
      "t": 24,
      "kind": "section"
    },
    {
      "t": 25.2,
      "kind": "goal"
    },
    {
      "t": 27,
      "kind": "step"
    },
    {
      "t": 27.5,
      "kind": "step"
    },
    {
      "t": 28,
      "kind": "step"
    },
    {
      "t": 28.5,
      "kind": "highlight"
    },
    {
      "t": 30,
      "kind": "focus"
    },
    {
      "t": 31.5,
      "kind": "focus"
    },
    {
      "t": 33,
      "kind": "focus"
    },
    {
      "t": 35,
      "kind": "click"
    },
    {
      "t": 36,
      "kind": "appear"
    },
    {
      "t": 38.8,
      "kind": "select"
    },
    {
      "t": 40,
      "kind": "click"
    },
    {
      "t": 41,
      "kind": "done"
    },
    {
      "t": 43.3,
      "kind": "card"
    },
    {
      "t": 45,
      "kind": "result"
    },
    {
      "t": 46,
      "kind": "result"
    },
    {
      "t": 47,
      "kind": "result"
    },
    {
      "t": 48,
      "kind": "highlight"
    },
    {
      "t": 50,
      "kind": "word"
    },
    {
      "t": 50.6,
      "kind": "word"
    },
    {
      "t": 52,
      "kind": "duck"
    },
    {
      "t": 54,
      "kind": "settle"
    },
    {
      "t": 55,
      "kind": "arrow"
    },
    {
      "t": 56,
      "kind": "final"
    }
  ]
};
