// GENERATED by tools/cuts.cjs (learn-45-page-subtitled). Edit tools/cuts.cjs, not this file.
FILM.TIMELINE = {
  "title": "learn",
  "variant": "learn-45-page-subtitled",
  "cut": 45,
  "ending": "page",
  "subtitles": true,
  "bpm": 120,
  "fps": 25,
  "width": 1920,
  "height": 1080,
  "duration": 45,
  "shots": [
    {
      "id": "s01",
      "file": "01-question.js",
      "start": 0,
      "end": 3,
      "mode": "none",
      "cut": 45,
      "title": "Знакомая ситуация",
      "brief": "see docs/storyboard.md s01"
    },
    {
      "id": "s02",
      "file": "02-guide.js",
      "start": 3,
      "end": 5,
      "mode": "none",
      "cut": 45,
      "title": "Появляется точка входа",
      "brief": "see docs/storyboard.md s02"
    },
    {
      "id": "s03",
      "file": "03-routes.js",
      "start": 5,
      "end": 7,
      "mode": "none",
      "cut": 45,
      "title": "Выбор из трёх задач",
      "brief": "see docs/storyboard.md s03"
    },
    {
      "id": "s04",
      "file": "04-agent.js",
      "start": 7,
      "end": 13,
      "mode": "none",
      "cut": 45,
      "title": "Собрать первого агента",
      "brief": "see docs/storyboard.md s04"
    },
    {
      "id": "s05",
      "file": "05-engineering.js",
      "start": 13,
      "end": 19,
      "mode": "none",
      "cut": 45,
      "title": "Разобраться в AI-инженерии",
      "brief": "see docs/storyboard.md s05"
    },
    {
      "id": "s06",
      "file": "06-project.js",
      "start": 19,
      "end": 25,
      "mode": "none",
      "cut": 45,
      "title": "Довести свой проект до результата",
      "brief": "see docs/storyboard.md s06",
      "transitionIn": {
        "kind": "fade",
        "dur": 0.32
      }
    },
    {
      "id": "s07",
      "file": "07-inside.js",
      "start": 25,
      "end": 30,
      "mode": "none",
      "cut": 45,
      "title": "Что внутри шага",
      "brief": "see docs/storyboard.md s07",
      "transitionIn": {
        "kind": "fade",
        "dur": 0.32
      }
    },
    {
      "id": "s08",
      "file": "08-practice.js",
      "start": 30,
      "end": 32,
      "mode": "none",
      "cut": 45,
      "title": "Сделать на своей задаче",
      "brief": "see docs/storyboard.md s08"
    },
    {
      "id": "s09",
      "file": "09-progress.js",
      "start": 32,
      "end": 34,
      "mode": "none",
      "cut": 45,
      "title": "Своё продвижение",
      "brief": "see docs/storyboard.md s09"
    },
    {
      "id": "s10",
      "file": "10-results.js",
      "start": 34,
      "end": 38,
      "mode": "none",
      "cut": 45,
      "title": "Что останется",
      "brief": "see docs/storyboard.md s10",
      "transitionIn": {
        "kind": "fade",
        "dur": 0.32
      }
    },
    {
      "id": "s11",
      "file": "11-free.js",
      "start": 38,
      "end": 41,
      "mode": "none",
      "cut": 45,
      "title": "Снять барьер",
      "brief": "see docs/storyboard.md s11"
    },
    {
      "id": "s12",
      "file": "12-cta.js",
      "start": 41,
      "end": 45,
      "mode": "none",
      "cut": 45,
      "title": "Выбрать маршрут",
      "brief": "see docs/storyboard.md s12"
    }
  ],
  "subs": [
    {
      "t0": 0.2,
      "t1": 2.9,
      "text": "Много видео про AI. С чего начать?"
    },
    {
      "t0": 3.1,
      "t1": 6.9,
      "text": "Выбери задачу. В гиде три бесплатных маршрута."
    },
    {
      "t0": 7.1,
      "t1": 12.9,
      "text": "Настрой агента: задай правила, дай ему задачу и проверь результат."
    },
    {
      "t0": 13.1,
      "t1": 18.9,
      "text": "Разберись в AI-инженерии: модель, инструменты, знания и проверка."
    },
    {
      "t0": 19.1,
      "t1": 24.9,
      "text": "Сдвинь свой проект с места: составь план на неделю."
    },
    {
      "t0": 25.1,
      "t1": 29.9,
      "text": "Внутри — видео, материалы, шаблоны и задания для практики."
    },
    {
      "t0": 30.1,
      "t1": 33.9,
      "text": "Примени к своей задаче. Проверь и отметь шаг."
    },
    {
      "t0": 34.1,
      "t1": 37.9,
      "text": "Результат — бриф, схема агента или план проекта."
    },
    {
      "t0": 38.1,
      "t1": 40.9,
      "text": "Бесплатно. Без регистрации."
    },
    {
      "t0": 41.2,
      "t1": 44.2,
      "text": "Выбери маршрут ниже. Начни сегодня."
    }
  ],
  "cues": [
    {
      "t": 0,
      "kind": "open"
    },
    {
      "t": 0.3,
      "kind": "tab"
    },
    {
      "t": 0.8,
      "kind": "tab"
    },
    {
      "t": 1,
      "kind": "question"
    },
    {
      "t": 3,
      "kind": "assemble"
    },
    {
      "t": 3.6,
      "kind": "logo"
    },
    {
      "t": 5,
      "kind": "tick"
    },
    {
      "t": 5.2,
      "kind": "tick"
    },
    {
      "t": 5.4,
      "kind": "tick"
    },
    {
      "t": 7,
      "kind": "section"
    },
    {
      "t": 8,
      "kind": "type"
    },
    {
      "t": 8.5,
      "kind": "type"
    },
    {
      "t": 9,
      "kind": "type"
    },
    {
      "t": 9.8,
      "kind": "handoff"
    },
    {
      "t": 11.9,
      "kind": "click"
    },
    {
      "t": 12.3,
      "kind": "verified"
    },
    {
      "t": 13,
      "kind": "section"
    },
    {
      "t": 14.2,
      "kind": "connect"
    },
    {
      "t": 15.1,
      "kind": "connect"
    },
    {
      "t": 16,
      "kind": "pulse"
    },
    {
      "t": 17.2,
      "kind": "connect"
    },
    {
      "t": 18.2,
      "kind": "sheet"
    },
    {
      "t": 19,
      "kind": "section"
    },
    {
      "t": 20.2,
      "kind": "goal"
    },
    {
      "t": 22,
      "kind": "step"
    },
    {
      "t": 22.5,
      "kind": "step"
    },
    {
      "t": 23,
      "kind": "step"
    },
    {
      "t": 23.5,
      "kind": "highlight"
    },
    {
      "t": 25,
      "kind": "focus"
    },
    {
      "t": 26.5,
      "kind": "focus"
    },
    {
      "t": 28,
      "kind": "focus"
    },
    {
      "t": 30,
      "kind": "click"
    },
    {
      "t": 30.5,
      "kind": "appear"
    },
    {
      "t": 31.4,
      "kind": "select"
    },
    {
      "t": 32.4,
      "kind": "click"
    },
    {
      "t": 33,
      "kind": "done"
    },
    {
      "t": 34,
      "kind": "result"
    },
    {
      "t": 34.5,
      "kind": "result"
    },
    {
      "t": 35,
      "kind": "result"
    },
    {
      "t": 35.8,
      "kind": "highlight"
    },
    {
      "t": 38,
      "kind": "word"
    },
    {
      "t": 38.25,
      "kind": "word"
    },
    {
      "t": 40,
      "kind": "duck"
    },
    {
      "t": 41,
      "kind": "settle"
    },
    {
      "t": 41.3,
      "kind": "arrow"
    },
    {
      "t": 41.5,
      "kind": "final"
    }
  ]
};
